### ISSUE TITLE
TypeError: text() got an unexpected keyword argument 'squash_space'

### ISSUE THREAD

**Issue by ferenczy** [gleitz/howdoi#208]
I have installed howdoi using pip in a Cygwin environment on Windows and when I run it, I get the following exception:

```
Traceback (most recent call last):
  File "/usr/bin/howdoi", line 11, in <module>
    sys.exit(command_line_runner())
  File "/usr/lib/python3.6/site-packages/howdoi/howdoi.py", line 311, in command_line_runner
    utf8_result = howdoi(args).encode('utf-8', 'ignore')
  File "/usr/lib/python3.6/site-packages/howdoi/howdoi.py", line 263, in howdoi
    return _get_instructions(args) or 'Sorry, couldn\'t find any help with that topic\n'
  File "/usr/lib/python3.6/site-packages/howdoi/howdoi.py", line 233, in _get_instructions
    answer = _get_answer(args, question_links)
  File "/usr/lib/python3.6/site-packages/howdoi/howdoi.py", line 205, in _get_answer
    text = _format_output(_get_text(instructions.eq(0)), args)
  File "/usr/lib/python3.6/site-packages/howdoi/howdoi.py", line 102, in _get_text
    return element.text(squash_space=False)
TypeError: text() got an unexpected keyword argument 'squash_space'
```

Python version: 3.6.4
howdoi version: 1.1.13

When I install it on native Windows Python, it's working fine.

**Comment by herrmanthegerman** [comment]
I observe this exception, too,  on WSL (Ubuntu for Windows) after updating from 1.1.12 to 1.1.13.

I installed `howdoi` by first cloning the git repository and then running (as root)  `python setup.py install`.

Python 2.7.12

**Comment by gleitz** [comment]
I would accept a PR with a try/catch around this (or perhaps a suggestion of version numbers to sue that would make this work on windows)

Also, the windows version of `howdoi` has been dead for a while. If anyone would like to build a `.exe` I would appreciate it.

**Comment by JohannesBuchner** [comment]
Have the same issue, but on Linux.
